'use strict';var Handlebars={};
(function(c,p){c.VERSION="1.0.0-rc.3";c.COMPILER_REVISION=3;c.REVISION_CHANGES={1:"<= 1.0.rc.2",2:"== 1.0.0-rc.3",3:">= 1.0.0-rc.4"};c.helpers={};c.partials={};var q=Object.prototype.toString;c.registerHelper=function(a,b,d){if(q.call(a)==="[object Object]"){if(d||b)throw new c.Exception("Arg not supported with multiple helpers");c.Utils.extend(this.helpers,a)}else{if(d)b.not=d;this.helpers[a]=b}};c.registerPartial=function(a,b){q.call(a)==="[object Object]"?c.Utils.extend(this.partials,a):this.partials[a]=
b};c.registerHelper("helperMissing",function(a){if(arguments.length===2)return p;else throw Error("Could not find property '"+a+"'");});c.registerHelper("blockHelperMissing",function(a,b){var d=b.inverse||function(){},e=b.fn,g=q.call(a);g==="[object Function]"&&(a=a.call(this));return a===true?e(this):a===false||a==null?d(this):g==="[object Array]"?a.length>0?c.helpers.each(a,b):d(this):e(a)});c.K=function(){};c.createFrame=Object.create||function(a){c.K.prototype=a;a=new c.K;c.K.prototype=null;return a};
c.logger={DEBUG:0,INFO:1,WARN:2,ERROR:3,level:3,methodMap:{0:"debug",1:"info",2:"warn",3:"error"},log:function(a,b){if(c.logger.level<=a){var d=c.logger.methodMap[a];typeof console!=="undefined"&&console[d]&&console[d].call(console,b)}}};c.log=function(a,b){c.logger.log(a,b)};c.registerHelper("each",function(a,b){var d=b.fn,e=b.inverse,g=0,h="",j;b.data&&(j=c.createFrame(b.data));if(a&&typeof a==="object")if(a instanceof Array)for(var i=a.length;g<i;g++){if(j)j.index=g;h+=d(a[g],{data:j})}else for(i in a)if(a.hasOwnProperty(i)){if(j)j.key=
i;h+=d(a[i],{data:j});g++}g===0&&(h=e(this));return h});c.registerHelper("if",function(a,b){q.call(a)==="[object Function]"&&(a=a.call(this));return!a||c.Utils.isEmpty(a)?b.inverse(this):b.fn(this)});c.registerHelper("unless",function(a,b){return c.helpers["if"].call(this,a,{fn:b.inverse,inverse:b.fn})});c.registerHelper("with",function(a,b){if(!c.Utils.isEmpty(a))return b.fn(a)});c.registerHelper("log",function(a,b){var d=b.data&&b.data.level!=null?parseInt(b.data.level,10):1;c.log(d,a)});var s=
function(){function a(){this.yy={}}var b={trace:function(){},yy:{},symbols_:{error:2,root:3,program:4,EOF:5,simpleInverse:6,statements:7,statement:8,openInverse:9,closeBlock:10,openBlock:11,mustache:12,partial:13,CONTENT:14,COMMENT:15,OPEN_BLOCK:16,inMustache:17,CLOSE:18,OPEN_INVERSE:19,OPEN_ENDBLOCK:20,path:21,OPEN:22,OPEN_UNESCAPED:23,OPEN_PARTIAL:24,partialName:25,params:26,hash:27,DATA:28,param:29,STRING:30,INTEGER:31,BOOLEAN:32,hashSegments:33,hashSegment:34,ID:35,EQUALS:36,PARTIAL_NAME:37,pathSegments:38,
SEP:39,$accept:0,$end:1},terminals_:{2:"error",5:"EOF",14:"CONTENT",15:"COMMENT",16:"OPEN_BLOCK",18:"CLOSE",19:"OPEN_INVERSE",20:"OPEN_ENDBLOCK",22:"OPEN",23:"OPEN_UNESCAPED",24:"OPEN_PARTIAL",28:"DATA",30:"STRING",31:"INTEGER",32:"BOOLEAN",35:"ID",36:"EQUALS",37:"PARTIAL_NAME",39:"SEP"},productions_:[0,[3,2],[4,2],[4,3],[4,2],[4,1],[4,1],[4,0],[7,1],[7,2],[8,3],[8,3],[8,1],[8,1],[8,1],[8,1],[11,3],[9,3],[10,3],[12,3],[12,3],[13,3],[13,4],[6,2],[17,3],[17,2],[17,2],[17,1],[17,1],[26,2],[26,1],[29,
1],[29,1],[29,1],[29,1],[29,1],[27,1],[33,2],[33,1],[34,3],[34,3],[34,3],[34,3],[34,3],[25,1],[21,1],[38,3],[38,1]],performAction:function(a,b,d,c,i,f){a=f.length-1;switch(i){case 1:return f[a-1];case 2:this.$=new c.ProgramNode([],f[a]);break;case 3:this.$=new c.ProgramNode(f[a-2],f[a]);break;case 4:this.$=new c.ProgramNode(f[a-1],[]);break;case 5:this.$=new c.ProgramNode(f[a]);break;case 6:this.$=new c.ProgramNode([],[]);break;case 7:this.$=new c.ProgramNode([]);break;case 8:this.$=[f[a]];break;
case 9:f[a-1].push(f[a]);this.$=f[a-1];break;case 10:this.$=new c.BlockNode(f[a-2],f[a-1].inverse,f[a-1],f[a]);break;case 11:this.$=new c.BlockNode(f[a-2],f[a-1],f[a-1].inverse,f[a]);break;case 12:this.$=f[a];break;case 13:this.$=f[a];break;case 14:this.$=new c.ContentNode(f[a]);break;case 15:this.$=new c.CommentNode(f[a]);break;case 16:this.$=new c.MustacheNode(f[a-1][0],f[a-1][1]);break;case 17:this.$=new c.MustacheNode(f[a-1][0],f[a-1][1]);break;case 18:this.$=f[a-1];break;case 19:this.$=new c.MustacheNode(f[a-
1][0],f[a-1][1]);break;case 20:this.$=new c.MustacheNode(f[a-1][0],f[a-1][1],true);break;case 21:this.$=new c.PartialNode(f[a-1]);break;case 22:this.$=new c.PartialNode(f[a-2],f[a-1]);break;case 24:this.$=[[f[a-2]].concat(f[a-1]),f[a]];break;case 25:this.$=[[f[a-1]].concat(f[a]),null];break;case 26:this.$=[[f[a-1]],f[a]];break;case 27:this.$=[[f[a]],null];break;case 28:this.$=[[new c.DataNode(f[a])],null];break;case 29:f[a-1].push(f[a]);this.$=f[a-1];break;case 30:this.$=[f[a]];break;case 31:this.$=
f[a];break;case 32:this.$=new c.StringNode(f[a]);break;case 33:this.$=new c.IntegerNode(f[a]);break;case 34:this.$=new c.BooleanNode(f[a]);break;case 35:this.$=new c.DataNode(f[a]);break;case 36:this.$=new c.HashNode(f[a]);break;case 37:f[a-1].push(f[a]);this.$=f[a-1];break;case 38:this.$=[f[a]];break;case 39:this.$=[f[a-2],f[a]];break;case 40:this.$=[f[a-2],new c.StringNode(f[a])];break;case 41:this.$=[f[a-2],new c.IntegerNode(f[a])];break;case 42:this.$=[f[a-2],new c.BooleanNode(f[a])];break;case 43:this.$=
[f[a-2],new c.DataNode(f[a])];break;case 44:this.$=new c.PartialNameNode(f[a]);break;case 45:this.$=new c.IdNode(f[a]);break;case 46:f[a-2].push(f[a]);this.$=f[a-2];break;case 47:this.$=[f[a]]}},table:[{3:1,4:2,5:[2,7],6:3,7:4,8:6,9:7,11:8,12:9,13:10,14:[1,11],15:[1,12],16:[1,13],19:[1,5],22:[1,14],23:[1,15],24:[1,16]},{1:[3]},{5:[1,17]},{5:[2,6],7:18,8:6,9:7,11:8,12:9,13:10,14:[1,11],15:[1,12],16:[1,13],19:[1,19],20:[2,6],22:[1,14],23:[1,15],24:[1,16]},{5:[2,5],6:20,8:21,9:7,11:8,12:9,13:10,14:[1,
11],15:[1,12],16:[1,13],19:[1,5],20:[2,5],22:[1,14],23:[1,15],24:[1,16]},{17:23,18:[1,22],21:24,28:[1,25],35:[1,27],38:26},{5:[2,8],14:[2,8],15:[2,8],16:[2,8],19:[2,8],20:[2,8],22:[2,8],23:[2,8],24:[2,8]},{4:28,6:3,7:4,8:6,9:7,11:8,12:9,13:10,14:[1,11],15:[1,12],16:[1,13],19:[1,5],20:[2,7],22:[1,14],23:[1,15],24:[1,16]},{4:29,6:3,7:4,8:6,9:7,11:8,12:9,13:10,14:[1,11],15:[1,12],16:[1,13],19:[1,5],20:[2,7],22:[1,14],23:[1,15],24:[1,16]},{5:[2,12],14:[2,12],15:[2,12],16:[2,12],19:[2,12],20:[2,12],22:[2,
12],23:[2,12],24:[2,12]},{5:[2,13],14:[2,13],15:[2,13],16:[2,13],19:[2,13],20:[2,13],22:[2,13],23:[2,13],24:[2,13]},{5:[2,14],14:[2,14],15:[2,14],16:[2,14],19:[2,14],20:[2,14],22:[2,14],23:[2,14],24:[2,14]},{5:[2,15],14:[2,15],15:[2,15],16:[2,15],19:[2,15],20:[2,15],22:[2,15],23:[2,15],24:[2,15]},{17:30,21:24,28:[1,25],35:[1,27],38:26},{17:31,21:24,28:[1,25],35:[1,27],38:26},{17:32,21:24,28:[1,25],35:[1,27],38:26},{25:33,37:[1,34]},{1:[2,1]},{5:[2,2],8:21,9:7,11:8,12:9,13:10,14:[1,11],15:[1,12],16:[1,
13],19:[1,19],20:[2,2],22:[1,14],23:[1,15],24:[1,16]},{17:23,21:24,28:[1,25],35:[1,27],38:26},{5:[2,4],7:35,8:6,9:7,11:8,12:9,13:10,14:[1,11],15:[1,12],16:[1,13],19:[1,19],20:[2,4],22:[1,14],23:[1,15],24:[1,16]},{5:[2,9],14:[2,9],15:[2,9],16:[2,9],19:[2,9],20:[2,9],22:[2,9],23:[2,9],24:[2,9]},{5:[2,23],14:[2,23],15:[2,23],16:[2,23],19:[2,23],20:[2,23],22:[2,23],23:[2,23],24:[2,23]},{18:[1,36]},{18:[2,27],21:41,26:37,27:38,28:[1,45],29:39,30:[1,42],31:[1,43],32:[1,44],33:40,34:46,35:[1,47],38:26},
{18:[2,28]},{18:[2,45],28:[2,45],30:[2,45],31:[2,45],32:[2,45],35:[2,45],39:[1,48]},{18:[2,47],28:[2,47],30:[2,47],31:[2,47],32:[2,47],35:[2,47],39:[2,47]},{10:49,20:[1,50]},{10:51,20:[1,50]},{18:[1,52]},{18:[1,53]},{18:[1,54]},{18:[1,55],21:56,35:[1,27],38:26},{18:[2,44],35:[2,44]},{5:[2,3],8:21,9:7,11:8,12:9,13:10,14:[1,11],15:[1,12],16:[1,13],19:[1,19],20:[2,3],22:[1,14],23:[1,15],24:[1,16]},{14:[2,17],15:[2,17],16:[2,17],19:[2,17],20:[2,17],22:[2,17],23:[2,17],24:[2,17]},{18:[2,25],21:41,27:57,
28:[1,45],29:58,30:[1,42],31:[1,43],32:[1,44],33:40,34:46,35:[1,47],38:26},{18:[2,26]},{18:[2,30],28:[2,30],30:[2,30],31:[2,30],32:[2,30],35:[2,30]},{18:[2,36],34:59,35:[1,60]},{18:[2,31],28:[2,31],30:[2,31],31:[2,31],32:[2,31],35:[2,31]},{18:[2,32],28:[2,32],30:[2,32],31:[2,32],32:[2,32],35:[2,32]},{18:[2,33],28:[2,33],30:[2,33],31:[2,33],32:[2,33],35:[2,33]},{18:[2,34],28:[2,34],30:[2,34],31:[2,34],32:[2,34],35:[2,34]},{18:[2,35],28:[2,35],30:[2,35],31:[2,35],32:[2,35],35:[2,35]},{18:[2,38],35:[2,
38]},{18:[2,47],28:[2,47],30:[2,47],31:[2,47],32:[2,47],35:[2,47],36:[1,61],39:[2,47]},{35:[1,62]},{5:[2,10],14:[2,10],15:[2,10],16:[2,10],19:[2,10],20:[2,10],22:[2,10],23:[2,10],24:[2,10]},{21:63,35:[1,27],38:26},{5:[2,11],14:[2,11],15:[2,11],16:[2,11],19:[2,11],20:[2,11],22:[2,11],23:[2,11],24:[2,11]},{14:[2,16],15:[2,16],16:[2,16],19:[2,16],20:[2,16],22:[2,16],23:[2,16],24:[2,16]},{5:[2,19],14:[2,19],15:[2,19],16:[2,19],19:[2,19],20:[2,19],22:[2,19],23:[2,19],24:[2,19]},{5:[2,20],14:[2,20],15:[2,
20],16:[2,20],19:[2,20],20:[2,20],22:[2,20],23:[2,20],24:[2,20]},{5:[2,21],14:[2,21],15:[2,21],16:[2,21],19:[2,21],20:[2,21],22:[2,21],23:[2,21],24:[2,21]},{18:[1,64]},{18:[2,24]},{18:[2,29],28:[2,29],30:[2,29],31:[2,29],32:[2,29],35:[2,29]},{18:[2,37],35:[2,37]},{36:[1,61]},{21:65,28:[1,69],30:[1,66],31:[1,67],32:[1,68],35:[1,27],38:26},{18:[2,46],28:[2,46],30:[2,46],31:[2,46],32:[2,46],35:[2,46],39:[2,46]},{18:[1,70]},{5:[2,22],14:[2,22],15:[2,22],16:[2,22],19:[2,22],20:[2,22],22:[2,22],23:[2,22],
24:[2,22]},{18:[2,39],35:[2,39]},{18:[2,40],35:[2,40]},{18:[2,41],35:[2,41]},{18:[2,42],35:[2,42]},{18:[2,43],35:[2,43]},{5:[2,18],14:[2,18],15:[2,18],16:[2,18],19:[2,18],20:[2,18],22:[2,18],23:[2,18],24:[2,18]}],defaultActions:{17:[2,1],25:[2,28],38:[2,26],57:[2,24]},parseError:function(a){throw Error(a);},parse:function(a){var b=[0],d=[null],c=[],i=this.table,f="",n=0,p=0,q=0;this.lexer.setInput(a);this.lexer.yy=this.yy;this.yy.lexer=this.lexer;this.yy.parser=this;if(typeof this.lexer.yylloc=="undefined")this.lexer.yylloc=
{};a=this.lexer.yylloc;c.push(a);var t=this.lexer.options&&this.lexer.options.ranges;if(typeof this.yy.parseError==="function")this.parseError=this.yy.parseError;for(var k,s,o,l,u={},r,m;;){o=b[b.length-1];if(this.defaultActions[o])l=this.defaultActions[o];else{if(k===null||typeof k=="undefined")k=void 0,k=this.lexer.lex()||1,typeof k!=="number"&&(k=this.symbols_[k]||k);l=i[o]&&i[o][k]}if(typeof l==="undefined"||!l.length||!l[0]){var v="";if(!q){m=[];for(r in i[o])this.terminals_[r]&&r>2&&m.push("'"+
this.terminals_[r]+"'");v=this.lexer.showPosition?"Parse error on line "+(n+1)+":\n"+this.lexer.showPosition()+"\nExpecting "+m.join(", ")+", got '"+(this.terminals_[k]||k)+"'":"Parse error on line "+(n+1)+": Unexpected "+(k==1?"end of input":"'"+(this.terminals_[k]||k)+"'");this.parseError(v,{text:this.lexer.match,token:this.terminals_[k]||k,line:this.lexer.yylineno,loc:a,expected:m})}}if(l[0]instanceof Array&&l.length>1)throw Error("Parse Error: multiple actions possible at state: "+o+", token: "+
k);switch(l[0]){case 1:b.push(k);d.push(this.lexer.yytext);c.push(this.lexer.yylloc);b.push(l[1]);k=null;s?(k=s,s=null):(p=this.lexer.yyleng,f=this.lexer.yytext,n=this.lexer.yylineno,a=this.lexer.yylloc,q>0&&q--);break;case 2:m=this.productions_[l[1]][1];u.$=d[d.length-m];u._$={first_line:c[c.length-(m||1)].first_line,last_line:c[c.length-1].last_line,first_column:c[c.length-(m||1)].first_column,last_column:c[c.length-1].last_column};if(t)u._$.range=[c[c.length-(m||1)].range[0],c[c.length-1].range[1]];
o=this.performAction.call(u,f,p,n,this.yy,l[1],d,c);if(typeof o!=="undefined")return o;m&&(b=b.slice(0,m*-2),d=d.slice(0,-1*m),c=c.slice(0,-1*m));b.push(this.productions_[l[1]][0]);d.push(u.$);c.push(u._$);l=i[b[b.length-2]][b[b.length-1]];b.push(l);break;case 3:return true}}return true}},d=function(){return{EOF:1,parseError:function(a,b){if(this.yy.parser)this.yy.parser.parseError(a,b);else throw Error(a);},setInput:function(a){this._input=a;this._more=this._less=this.done=false;this.yylineno=this.yyleng=
0;this.yytext=this.matched=this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};if(this.options.ranges)this.yylloc.range=[0,0];this.offset=0;return this},input:function(){var a=this._input[0];this.yytext+=a;this.yyleng++;this.offset++;this.match+=a;this.matched+=a;a.match(/(?:\r\n?|\n).*/g)?(this.yylineno++,this.yylloc.last_line++):this.yylloc.last_column++;this.options.ranges&&this.yylloc.range[1]++;this._input=this._input.slice(1);return a},
unput:function(a){var b=a.length,d=a.split(/(?:\r\n?|\n)/g);this._input=a+this._input;this.yytext=this.yytext.substr(0,this.yytext.length-b-1);this.offset-=b;a=this.match.split(/(?:\r\n?|\n)/g);this.match=this.match.substr(0,this.match.length-1);this.matched=this.matched.substr(0,this.matched.length-1);d.length-1&&(this.yylineno-=d.length-1);var c=this.yylloc.range;this.yylloc={first_line:this.yylloc.first_line,last_line:this.yylineno+1,first_column:this.yylloc.first_column,last_column:d?(d.length===
a.length?this.yylloc.first_column:0)+a[a.length-d.length].length-d[0].length:this.yylloc.first_column-b};if(this.options.ranges)this.yylloc.range=[c[0],c[0]+this.yyleng-b];return this},more:function(){this._more=true;return this},less:function(a){this.unput(this.match.slice(a))},pastInput:function(){var a=this.matched.substr(0,this.matched.length-this.match.length);return(a.length>20?"...":"")+a.substr(-20).replace(/\n/g,"")},upcomingInput:function(){var a=this.match;a.length<20&&(a+=this._input.substr(0,
20-a.length));return(a.substr(0,20)+(a.length>20?"...":"")).replace(/\n/g,"")},showPosition:function(){var a=this.pastInput(),b=Array(a.length+1).join("-");return a+this.upcomingInput()+"\n"+b+"^"},next:function(){if(this.done)return this.EOF;if(!this._input)this.done=true;var a,b,d;if(!this._more)this.match=this.yytext="";for(var c=this._currentRules(),i=0;i<c.length;i++)if((b=this._input.match(this.rules[c[i]]))&&(!a||b[0].length>a[0].length))if(a=b,d=i,!this.options.flex)break;if(a){(b=a[0].match(/(?:\r\n?|\n).*/g))&&
(this.yylineno+=b.length);this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+1,first_column:this.yylloc.last_column,last_column:b?b[b.length-1].length-b[b.length-1].match(/\r?\n?/)[0].length:this.yylloc.last_column+a[0].length};this.yytext+=a[0];this.match+=a[0];this.matches=a;this.yyleng=this.yytext.length;if(this.options.ranges)this.yylloc.range=[this.offset,this.offset+=this.yyleng];this._more=false;this._input=this._input.slice(a[0].length);this.matched+=a[0];a=this.performAction.call(this,
this.yy,this,c[d],this.conditionStack[this.conditionStack.length-1]);if(this.done&&this._input)this.done=false;if(a)return a;else return}return this._input===""?this.EOF:this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var a=this.next();return typeof a!=="undefined"?a:this.lex()},begin:function(a){this.conditionStack.push(a)},popState:function(){return this.conditionStack.pop()},_currentRules:function(){return this.conditions[this.conditionStack[this.conditionStack.length-
1]].rules},topState:function(){return this.conditionStack[this.conditionStack.length-2]},pushState:function(a){this.begin(a)},options:{},performAction:function(a,b,d){switch(d){case 0:return b.yytext="\\",14;case 1:b.yytext.slice(-1)!=="\\"&&this.begin("mu");if(b.yytext.slice(-1)==="\\")b.yytext=b.yytext.substr(0,b.yyleng-1),this.begin("emu");if(b.yytext)return 14;break;case 2:return 14;case 3:b.yytext.slice(-1)!=="\\"&&this.popState();if(b.yytext.slice(-1)==="\\")b.yytext=b.yytext.substr(0,b.yyleng-
1);return 14;case 4:return b.yytext=b.yytext.substr(0,b.yyleng-4),this.popState(),15;case 5:return this.begin("par"),24;case 6:return 16;case 7:return 20;case 8:return 19;case 9:return 19;case 10:return 23;case 11:return 23;case 12:this.popState();this.begin("com");break;case 13:return b.yytext=b.yytext.substr(3,b.yyleng-5),this.popState(),15;case 14:return 22;case 15:return 36;case 16:return 35;case 17:return 35;case 18:return 39;case 20:return this.popState(),18;case 21:return this.popState(),18;
case 22:return b.yytext=b.yytext.substr(1,b.yyleng-2).replace(/\\"/g,'"'),30;case 23:return b.yytext=b.yytext.substr(1,b.yyleng-2).replace(/\\'/g,"'"),30;case 24:return b.yytext=b.yytext.substr(1),28;case 25:return 32;case 26:return 32;case 27:return 31;case 28:return 35;case 29:return b.yytext=b.yytext.substr(1,b.yyleng-2),35;case 30:return"INVALID";case 32:return this.popState(),37;case 33:return 5}},rules:[/^(?:\\\\(?=(\{\{)))/,/^(?:[^\x00]*?(?=(\{\{)))/,/^(?:[^\x00]+)/,/^(?:[^\x00]{2,}?(?=(\{\{|$)))/,
/^(?:[\s\S]*?--\}\})/,/^(?:\{\{>)/,/^(?:\{\{#)/,/^(?:\{\{\/)/,/^(?:\{\{\^)/,/^(?:\{\{\s*else\b)/,/^(?:\{\{\{)/,/^(?:\{\{&)/,/^(?:\{\{!--)/,/^(?:\{\{![\s\S]*?\}\})/,/^(?:\{\{)/,/^(?:=)/,/^(?:\.(?=[}/ ]))/,/^(?:\.\.)/,/^(?:[\/.])/,/^(?:\s+)/,/^(?:\}\}\})/,/^(?:\}\})/,/^(?:"(\\["]|[^"])*")/,/^(?:'(\\[']|[^'])*')/,/^(?:@[a-zA-Z]+)/,/^(?:true(?=[}\s]))/,/^(?:false(?=[}\s]))/,/^(?:-?[0-9]+(?=[}\s]))/,/^(?:[a-zA-Z0-9_$:-]+(?=[=}\s\/.]))/,/^(?:\[[^\]]*\])/,/^(?:.)/,/^(?:\s+)/,/^(?:[a-zA-Z0-9_$-\/]+)/,/^(?:$)/],
conditions:{mu:{rules:[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,33],inclusive:false},emu:{rules:[3],inclusive:false},com:{rules:[4],inclusive:false},par:{rules:[31,32],inclusive:false},INITIAL:{rules:[0,1,2,33],inclusive:true}}}}();b.lexer=d;a.prototype=b;b.Parser=a;return new a}();c.Parser=s;c.parse=function(a){if(a.constructor===c.AST.ProgramNode)return a;c.Parser.yy=c.AST;return c.Parser.parse(a)};c.AST={};c.AST.ProgramNode=function(a,b){this.type="program";this.statements=
a;if(b)this.inverse=new c.AST.ProgramNode(b)};c.AST.MustacheNode=function(a,b,d){var e;this.type="mustache";this.escaped=!d;this.hash=b;d=this.id=a[0];e=this.params=a.slice(1),a=e;this.isHelper=(this.eligibleHelper=d.isSimple)&&(a.length||b)};c.AST.PartialNode=function(a,b){this.type="partial";this.partialName=a;this.context=b};c.AST.BlockNode=function(a,b,d,e){var g=a.id;if(g.original!==e.original)throw new c.Exception(g.original+" doesn't match "+e.original);this.type="block";this.mustache=a;this.program=
b;if((this.inverse=d)&&!this.program)this.isInverse=true};c.AST.ContentNode=function(a){this.type="content";this.string=a};c.AST.HashNode=function(a){this.type="hash";this.pairs=a};c.AST.IdNode=function(a){this.type="ID";this.original=a.join(".");for(var b=[],d=0,e=0,g=a.length;e<g;e++){var h=a[e];if(h===".."||h==="."||h==="this")if(b.length>0)throw new c.Exception("Invalid path: "+this.original);else h===".."?d++:this.isScoped=true;else b.push(h)}this.parts=b;this.string=b.join(".");this.depth=d;
this.isSimple=a.length===1&&!this.isScoped&&d===0;this.stringModeValue=this.string};c.AST.PartialNameNode=function(a){this.type="PARTIAL_NAME";this.name=a};c.AST.DataNode=function(a){this.type="DATA";this.id=a};c.AST.StringNode=function(a){this.type="STRING";this.stringModeValue=this.string=a};c.AST.IntegerNode=function(a){this.type="INTEGER";this.integer=a;this.stringModeValue=Number(a)};c.AST.BooleanNode=function(a){this.type="BOOLEAN";this.bool=a;this.stringModeValue=a==="true"};c.AST.CommentNode=
function(a){this.type="comment";this.comment=a};var v="description,fileName,lineNumber,message,name,number,stack".split(",");c.Exception=function(a){for(var b=Error.prototype.constructor.apply(this,arguments),d=0;d<v.length;d++)this[v[d]]=b[v[d]]};c.Exception.prototype=Error();c.SafeString=function(a){this.string=a};c.SafeString.prototype.toString=function(){return this.string.toString()};var y={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","`":"&#x60;"},z=/[&<>"'`]/g,A=/[&<>"'`]/,B=
function(a){return y[a]||"&amp;"};c.Utils={extend:function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])},escapeExpression:function(a){if(a instanceof c.SafeString)return a.toString();else if(a==null||a===false)return"";a=a.toString();return!A.test(a)?a:a.replace(z,B)},isEmpty:function(a){return!a&&a!==0?true:q.call(a)==="[object Array]"&&a.length===0?true:false}};var r=c.Compiler=function(){},n=c.JavaScriptCompiler=function(){};r.prototype={compiler:r,disassemble:function(){for(var a=this.opcodes,
b,d=[],c,g,h=0,j=a.length;h<j;h++)if(b=a[h],b.opcode==="DECLARE")d.push("DECLARE "+b.name+"="+b.value);else{c=[];for(var i=0;i<b.args.length;i++)g=b.args[i],typeof g==="string"&&(g='"'+g.replace("\n","\\n")+'"'),c.push(g);d.push(b.opcode+" "+c.join(" "))}return d.join("\n")},equals:function(a){var b=this.opcodes.length;if(a.opcodes.length!==b)return false;for(var d=0;d<b;d++){var c=this.opcodes[d],g=a.opcodes[d];if(c.opcode!==g.opcode||c.args.length!==g.args.length)return false;for(var h=0;h<c.args.length;h++)if(c.args[h]!==
g.args[h])return false}b=this.children.length;if(a.children.length!==b)return false;for(d=0;d<b;d++)if(!this.children[d].equals(a.children[d]))return false;return true},guid:0,compile:function(a,b){this.children=[];this.depths={list:[]};this.options=b;var d=this.options.knownHelpers;this.options.knownHelpers={helperMissing:true,blockHelperMissing:true,each:true,"if":true,unless:true,"with":true,log:true};if(d)for(var c in d)this.options.knownHelpers[c]=d[c];return this.program(a)},accept:function(a){return this[a.type](a)},
program:function(a){var a=a.statements,b;this.opcodes=[];for(var d=0,c=a.length;d<c;d++)b=a[d],this[b.type](b);this.isSimple=c===1;this.depths.list=this.depths.list.sort(function(a,b){return a-b});return this},compileProgram:function(a){var a=(new this.compiler).compile(a,this.options),b=this.guid++,d;this.usePartial=this.usePartial||a.usePartial;this.children[b]=a;for(var c=0,g=a.depths.list.length;c<g;c++)d=a.depths.list[c],d<2||this.addDepth(d-1);return b},block:function(a){var b=a.mustache,d=
a.program,a=a.inverse;d&&(d=this.compileProgram(d));a&&(a=this.compileProgram(a));var c=this.classifyMustache(b);c==="helper"?this.helperMustache(b,d,a):c==="simple"?(this.simpleMustache(b),this.opcode("pushProgram",d),this.opcode("pushProgram",a),this.opcode("emptyHash"),this.opcode("blockValue")):(this.ambiguousMustache(b,d,a),this.opcode("pushProgram",d),this.opcode("pushProgram",a),this.opcode("emptyHash"),this.opcode("ambiguousBlockValue"));this.opcode("append")},hash:function(a){var a=a.pairs,
b,d;this.opcode("pushHash");for(var c=0,g=a.length;c<g;c++)b=a[c],d=b[1],this.options.stringParams?(d.depth&&this.addDepth(d.depth),this.opcode("getContext",d.depth||0),this.opcode("pushStringParam",d.stringModeValue,d.type)):this.accept(d),this.opcode("assignToHash",b[0]);this.opcode("popHash")},partial:function(a){var b=a.partialName;this.usePartial=true;a.context?this.ID(a.context):this.opcode("push","depth0");this.opcode("invokePartial",b.name);this.opcode("append")},content:function(a){this.opcode("appendContent",
a.string)},mustache:function(a){var b=this.options,d=this.classifyMustache(a);d==="simple"?this.simpleMustache(a):d==="helper"?this.helperMustache(a):this.ambiguousMustache(a);a.escaped&&!b.noEscape?this.opcode("appendEscaped"):this.opcode("append")},ambiguousMustache:function(a,b,d){var a=a.id,c=a.parts[0],g=b!=null||d!=null;this.opcode("getContext",a.depth);this.opcode("pushProgram",b);this.opcode("pushProgram",d);this.opcode("invokeAmbiguous",c,g)},simpleMustache:function(a){a=a.id;a.type==="DATA"?
this.DATA(a):a.parts.length?this.ID(a):(this.addDepth(a.depth),this.opcode("getContext",a.depth),this.opcode("pushContext"));this.opcode("resolvePossibleLambda")},helperMustache:function(a,b,d){b=this.setupFullMustacheParams(a,b,d);a=a.id.parts[0];if(this.options.knownHelpers[a])this.opcode("invokeKnownHelper",b.length,a);else if(this.options.knownHelpersOnly)throw Error("You specified knownHelpersOnly, but used the unknown helper "+a);else this.opcode("invokeHelper",b.length,a)},ID:function(a){this.addDepth(a.depth);
this.opcode("getContext",a.depth);a.parts[0]?this.opcode("lookupOnContext",a.parts[0]):this.opcode("pushContext");for(var b=1,d=a.parts.length;b<d;b++)this.opcode("lookup",a.parts[b])},DATA:function(a){this.options.data=true;this.opcode("lookupData",a.id)},STRING:function(a){this.opcode("pushString",a.string)},INTEGER:function(a){this.opcode("pushLiteral",a.integer)},BOOLEAN:function(a){this.opcode("pushLiteral",a.bool)},comment:function(){},opcode:function(a){this.opcodes.push({opcode:a,args:[].slice.call(arguments,
1)})},declare:function(a,b){this.opcodes.push({opcode:"DECLARE",name:a,value:b})},addDepth:function(a){if(isNaN(a))throw Error("EWOT");a!==0&&!this.depths[a]&&(this.depths[a]=true,this.depths.list.push(a))},classifyMustache:function(a){var b=a.isHelper,d=a.eligibleHelper,c=this.options;d&&!b&&(c.knownHelpers[a.id.parts[0]]?b=true:c.knownHelpersOnly&&(d=false));return b?"helper":d?"ambiguous":"simple"},pushParams:function(a){for(var b=a.length,d;b--;)if(d=a[b],this.options.stringParams)d.depth&&this.addDepth(d.depth),
this.opcode("getContext",d.depth||0),this.opcode("pushStringParam",d.stringModeValue,d.type);else this[d.type](d)},setupMustacheParams:function(a){var b=a.params;this.pushParams(b);a.hash?this.hash(a.hash):this.opcode("emptyHash");return b},setupFullMustacheParams:function(a,b,d){var c=a.params;this.pushParams(c);this.opcode("pushProgram",b);this.opcode("pushProgram",d);a.hash?this.hash(a.hash):this.opcode("emptyHash");return c}};var t=function(a){this.value=a};n.prototype={nameLookup:function(a,
b){return/^[0-9]+$/.test(b)?a+"["+b+"]":n.isValidJavaScriptVariableName(b)?a+"."+b:a+"['"+b+"']"},appendToBuffer:function(a){return this.environment.isSimple?"return "+a+";":{appendToBuffer:true,content:a,toString:function(){return"buffer += "+a+";"}}},initializeBuffer:function(){return this.quotedString("")},namespace:"Handlebars",compile:function(a,b,d,e){this.environment=a;this.options=b||{};c.log(c.logger.DEBUG,this.environment.disassemble()+"\n\n");this.name=this.environment.name;this.isChild=
!!d;this.context=d||{programs:[],environments:[],aliases:{}};this.preamble();this.stackSlot=0;this.stackVars=[];this.registers={list:[]};this.compileStack=[];this.inlineStack=[];this.compileChildren(a,b);a=a.opcodes;this.i=0;for(w=a.length;this.i<w;this.i++)b=a[this.i],b.opcode==="DECLARE"?this[b.name]=b.value:this[b.opcode].apply(this,b.args);return this.createFunctionContext(e)},nextOpcode:function(){return this.environment.opcodes[this.i+1]},eat:function(){this.i+=1},preamble:function(){var a=
[];if(this.isChild)a.push("");else{var b=this.namespace,d="helpers = helpers || "+b+".helpers;";this.environment.usePartial&&(d=d+" partials = partials || "+b+".partials;");this.options.data&&(d+=" data = data || {};");a.push(d)}this.environment.isSimple?a.push(""):a.push(", buffer = "+this.initializeBuffer());this.lastContext=0;this.source=a},createFunctionContext:function(a){var b=this.stackVars.concat(this.registers.list);b.length>0&&(this.source[1]=this.source[1]+", "+b.join(", "));if(!this.isChild)for(var d in this.context.aliases)this.source[1]=
this.source[1]+", "+d+"="+this.context.aliases[d];this.source[1]&&(this.source[1]="var "+this.source[1].substring(2)+";");this.isChild||(this.source[1]+="\n"+this.context.programs.join("\n")+"\n");this.environment.isSimple||this.source.push("return buffer;");b=this.isChild?["depth0","data"]:["Handlebars","depth0","helpers","partials","data"];d=0;for(var e=this.environment.depths.list.length;d<e;d++)b.push("depth"+this.environment.depths.list[d]);d=this.mergeSource();if(!this.isChild)e=c.COMPILER_REVISION,
d="this.compilerInfo = ["+e+",'"+c.REVISION_CHANGES[e]+"'];\n"+d;return a?(b.push(d),Function.apply(this,b)):(a="function "+(this.name||"")+"("+b.join(",")+") {\n  "+d+"}",c.log(c.logger.DEBUG,a+"\n\n"),a)},mergeSource:function(){for(var a="",b,d=0,c=this.source.length;d<c;d++){var g=this.source[d];g.appendToBuffer?b=b?b+"\n    + "+g.content:g.content:(b&&(a+="buffer += "+b+";\n  ",b=p),a+=g+"\n  ")}return a},blockValue:function(){this.context.aliases.blockHelperMissing="helpers.blockHelperMissing";
var a=["depth0"];this.setupParams(0,a);this.replaceStack(function(b){a.splice(1,0,b);return"blockHelperMissing.call("+a.join(", ")+")"})},ambiguousBlockValue:function(){this.context.aliases.blockHelperMissing="helpers.blockHelperMissing";var a=["depth0"];this.setupParams(0,a);var b=this.topStack();a.splice(1,0,b);a[a.length-1]="options";this.source.push("if (!"+this.lastHelper+") { "+b+" = blockHelperMissing.call("+a.join(", ")+"); }")},appendContent:function(a){this.source.push(this.appendToBuffer(this.quotedString(a)))},
append:function(){this.flushInline();var a=this.popStack();this.source.push("if("+a+" || "+a+" === 0) { "+this.appendToBuffer(a)+" }");this.environment.isSimple&&this.source.push("else { "+this.appendToBuffer("''")+" }")},appendEscaped:function(){this.context.aliases.escapeExpression="this.escapeExpression";this.source.push(this.appendToBuffer("escapeExpression("+this.popStack()+")"))},getContext:function(a){if(this.lastContext!==a)this.lastContext=a},lookupOnContext:function(a){this.push(this.nameLookup("depth"+
this.lastContext,a,"context"))},pushContext:function(){this.pushStackLiteral("depth"+this.lastContext)},resolvePossibleLambda:function(){this.context.aliases.functionType='"function"';this.replaceStack(function(a){return"typeof "+a+" === functionType ? "+a+".apply(depth0) : "+a})},lookup:function(a){this.replaceStack(function(b){return b+" == null || "+b+" === false ? "+b+" : "+this.nameLookup(b,a,"context")})},lookupData:function(a){this.push(this.nameLookup("data",a,"data"))},pushStringParam:function(a,
b){this.pushStackLiteral("depth"+this.lastContext);this.pushString(b);typeof a==="string"?this.pushString(a):this.pushStackLiteral(a)},emptyHash:function(){this.pushStackLiteral("{}");this.options.stringParams&&(this.register("hashTypes","{}"),this.register("hashContexts","{}"))},pushHash:function(){this.hash={values:[],types:[],contexts:[]}},popHash:function(){var a=this.hash;this.hash=p;this.options.stringParams&&(this.register("hashContexts","{"+a.contexts.join(",")+"}"),this.register("hashTypes",
"{"+a.types.join(",")+"}"));this.push("{\n    "+a.values.join(",\n    ")+"\n  }")},pushString:function(a){this.pushStackLiteral(this.quotedString(a))},push:function(a){this.inlineStack.push(a);return a},pushLiteral:function(a){this.pushStackLiteral(a)},pushProgram:function(a){a!=null?this.pushStackLiteral(this.programExpression(a)):this.pushStackLiteral(null)},invokeHelper:function(a,b){this.context.aliases.helperMissing="helpers.helperMissing";var d=this.lastHelper=this.setupHelper(a,b,true);this.push(d.name);
this.replaceStack(function(a){return a+" ? "+a+".call("+d.callParams+") : helperMissing.call("+d.helperMissingParams+")"})},invokeKnownHelper:function(a,b){var d=this.setupHelper(a,b);this.push(d.name+".call("+d.callParams+")")},invokeAmbiguous:function(a,b){this.context.aliases.functionType='"function"';this.pushStackLiteral("{}");var d=this.setupHelper(0,a,b),c=this.lastHelper=this.nameLookup("helpers",a,"helper"),g=this.nameLookup("depth"+this.lastContext,a,"context"),h=this.nextStack();this.source.push("if ("+
h+" = "+c+") { "+h+" = "+h+".call("+d.callParams+"); }");this.source.push("else { "+h+" = "+g+"; "+h+" = typeof "+h+" === functionType ? "+h+".apply(depth0) : "+h+"; }")},invokePartial:function(a){a=[this.nameLookup("partials",a,"partial"),"'"+a+"'",this.popStack(),"helpers","partials"];this.options.data&&a.push("data");this.context.aliases.self="this";this.push("self.invokePartial("+a.join(", ")+")")},assignToHash:function(a){var b=this.popStack(),d,c;this.options.stringParams&&(c=this.popStack(),
d=this.popStack());var g=this.hash;d&&g.contexts.push("'"+a+"': "+d);c&&g.types.push("'"+a+"': "+c);g.values.push("'"+a+"': ("+b+")")},compiler:n,compileChildren:function(a,b){for(var d=a.children,c,g,h=0,j=d.length;h<j;h++){c=d[h];g=new this.compiler;var i=this.matchExistingProgram(c);i==null?(this.context.programs.push(""),i=this.context.programs.length,c.index=i,c.name="program"+i,this.context.programs[i]=g.compile(c,b,this.context),this.context.environments[i]=c):(c.index=i,c.name="program"+i)}},
matchExistingProgram:function(a){for(var b=0,d=this.context.environments.length;b<d;b++){var c=this.context.environments[b];if(c&&c.equals(a))return b}},programExpression:function(a){this.context.aliases.self="this";if(a==null)return"self.noop";for(var b=this.environment.children[a],a=b.depths.list,c=[b.index,b.name,"data"],e=0,g=a.length;e<g;e++)b=a[e],b===1?c.push("depth0"):c.push("depth"+(b-1));return(a.length===0?"self.program(":"self.programWithDepth(")+c.join(", ")+")"},register:function(a,
b){this.useRegister(a);this.source.push(a+" = "+b+";")},useRegister:function(a){this.registers[a]||(this.registers[a]=true,this.registers.list.push(a))},pushStackLiteral:function(a){return this.push(new t(a))},pushStack:function(a){this.flushInline();var b=this.incrStack();a&&this.source.push(b+" = "+a+";");this.compileStack.push(b);return b},replaceStack:function(a){var b="",c=this.isInline(),e;c?(e=this.popStack(true),e instanceof t?e=e.value:(b="("+this.push(this.stackSlot?this.topStackName():
this.incrStack())+" = "+e+"),",e=this.topStack())):e=this.topStack();a=a.call(this,e);c?((this.inlineStack.length||this.compileStack.length)&&this.popStack(),this.push("("+b+a+")")):(/^stack/.test(e)||(e=this.nextStack()),this.source.push(e+" = ("+b+a+");"));return e},nextStack:function(){return this.pushStack()},incrStack:function(){this.stackSlot++;this.stackSlot>this.stackVars.length&&this.stackVars.push("stack"+this.stackSlot);return this.topStackName()},topStackName:function(){return"stack"+
this.stackSlot},flushInline:function(){var a=this.inlineStack;if(a.length){this.inlineStack=[];for(var b=0,c=a.length;b<c;b++){var e=a[b];e instanceof t?this.compileStack.push(e):this.pushStack(e)}}},isInline:function(){return this.inlineStack.length},popStack:function(a){var b=this.isInline(),c=(b?this.inlineStack:this.compileStack).pop();return!a&&c instanceof t?c.value:(b||this.stackSlot--,c)},topStack:function(a){var b=this.isInline()?this.inlineStack:this.compileStack,b=b[b.length-1];return!a&&
b instanceof t?b.value:b},quotedString:function(a){return'"'+a.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\u2028/g,"\\u2028").replace(/\u2029/g,"\\u2029")+'"'},setupHelper:function(a,b,c){var e=[];this.setupParams(a,e,c);a=this.nameLookup("helpers",b,"helper");return{params:e,name:a,callParams:["depth0"].concat(e).join(", "),helperMissingParams:c&&["depth0",this.quotedString(b)].concat(e).join(", ")}},setupParams:function(a,b,c){var e=[],g=[],h=[],
j,i;e.push("hash:"+this.popStack());j=this.popStack();if((i=this.popStack())||j){if(!i)this.context.aliases.self="this",i="self.noop";if(!j)this.context.aliases.self="this",j="self.noop";e.push("inverse:"+j);e.push("fn:"+i)}for(i=0;i<a;i++)j=this.popStack(),b.push(j),this.options.stringParams&&(h.push(this.popStack()),g.push(this.popStack()));this.options.stringParams&&(e.push("contexts:["+g.join(",")+"]"),e.push("types:["+h.join(",")+"]"),e.push("hashContexts:hashContexts"),e.push("hashTypes:hashTypes"));
this.options.data&&e.push("data:data");e="{"+e.join(",")+"}";c?(this.register("options",e),b.push("options")):b.push(e);return b.join(", ")}};for(var s="break else new var case finally return void catch for switch while continue function this with default if throw delete in try do instanceof typeof abstract enum int short boolean export interface static byte extends long super char final native synchronized class float package throws const goto private transient debugger implements protected volatile double import public let yield".split(" "),
C=n.RESERVED_WORDS={},x=0,w=s.length;x<w;x++)C[s[x]]=true;n.isValidJavaScriptVariableName=function(a){return!n.RESERVED_WORDS[a]&&/^[a-zA-Z_$][0-9a-zA-Z_$]+$/.test(a)?true:false};c.precompile=function(a,b){if(a==null||typeof a!=="string"&&a.constructor!==c.AST.ProgramNode)throw new c.Exception("You must pass a string or Handlebars AST to Handlebars.precompile. You passed "+a);b=b||{};if(!("data"in b))b.data=true;var d=c.parse(a),d=(new r).compile(d,b);return(new n).compile(d,b)};c.compile=function(a,
b){if(a==null||typeof a!=="string"&&a.constructor!==c.AST.ProgramNode)throw new c.Exception("You must pass a string or Handlebars AST to Handlebars.compile. You passed "+a);b=b||{};if(!("data"in b))b.data=true;var d;return function(e,g){if(!d){var h=c.parse(a),h=(new r).compile(h,b),h=(new n).compile(h,b,p,true);d=c.template(h)}return d.call(this,e,g)}};c.VM={template:function(a){var b={escapeExpression:c.Utils.escapeExpression,invokePartial:c.VM.invokePartial,programs:[],program:function(a,b,g){var h=
this.programs[a];g?h=c.VM.program(a,b,g):h||(h=this.programs[a]=c.VM.program(a,b));return h},programWithDepth:c.VM.programWithDepth,noop:c.VM.noop,compilerInfo:null};return function(d,e){var e=e||{},g=a.call(b,c,d,e.helpers,e.partials,e.data),h=b.compilerInfo||[],j=h[0]||1,i=c.COMPILER_REVISION;if(j!==i)if(j<i)throw"Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version ("+c.REVISION_CHANGES[i]+") or downgrade your runtime to an older version ("+
c.REVISION_CHANGES[j]+").";else throw"Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version ("+h[1]+").";return g}},programWithDepth:function(a,b,c){var e=Array.prototype.slice.call(arguments,3),g=function(a,g){g=g||{};return b.apply(this,[a,g.data||c].concat(e))};g.program=a;g.depth=e.length;return g},program:function(a,b,c){var e=function(a,e){e=e||{};return b(a,e.data||c)};e.program=a;e.depth=0;return e},noop:function(){return""},
invokePartial:function(a,b,d,e,g,h){e={helpers:e,partials:g,data:h};if(a===p)throw new c.Exception("The partial "+b+" could not be found");else if(a instanceof Function)return a(d,e);else if(c.compile)return g[b]=c.compile(a,{data:h!==p}),g[b](d,e);else throw new c.Exception("The partial "+b+" could not be compiled when running in runtime-only mode");}};c.template=c.VM.template})(Handlebars);
